Карианство (анг. carianity)
===========================

:toc:

== Суть веры карианской

Карианство - это мировоззрение, вера, религия, основанная на представлении о достаточности разума человека и человечества для решения всех стоящих перед разумной жизнью проблем. Кариане верят, что разум, вооружённый научным методом, может преодолеть все трудности могущие встать на пути выживания разумной жизни во Вселенной. Это представление есть вера, оно не может быть доказано или опровергнуто научными методами, хотя вся история развития цивилизации укрепляет сию веру. Кариане верят, что разумной расе не нужны никакие сверхъестественные опекуны-попечители, человечеству давно пора повзрослеть, начать думать самостоятельно и принять ответственность за свои действия.

Дополнительные пояснения:

1. Карианство опирается на разум, на научный метод, а значит на логику.
2. Вопрос существования всемогущих сверхъестественных существ находится вне науки (недоказуем и неопровергаем), поэтому это вопрос веры, но он и не имеет значения для кариан - неважно есть или нет какие-то сверхъестественные существа нужно жить своим умом, а все неизвестное стремиться познать.

== Цель

Карианство определяет цель индивидуума и социума как баланс между двумя основными целями:

1. Обеспечить индивидуумам свободную жизнь с возможностью удовлетворить все базовые потребности не теряя свободы
2. Организовать общество так, чтобы непрерывно повышать степень устойчивости разумной цивилизации к превратностям Вселенной (а значит развивать науку и технику, вести космическую экспансию, повышать эффективность как отдельных индивидуумов, так и социума в целом)

т.е. нужно развиваться, вести борьбу с хаосом, но не ценою жизни и здоровья граждан и без создания излишних рисков (устойчивое развитие)

== Карианская мораль

Для того чтобы привнести в общество правила поведения нет никакой необходимости во внешней силе, разумные существа вполне могут сами понять что сотрудничество с другими выгодно, а для того чтобы сотрудничество состоялось необходимо уважать интересы других.

Общий принцип относительно простой - "поступай с другими так, как хотел бы чтобы поступали с тобой" или "твоя свобода ограничена свободой других" (золотое правило этики), однако не так просто определить что есть аксиома, а что можно вывести из аксиом.
Как минимум, понятно, что правила жизни общества должны включать требования к поведению, а не мотивации к нему. Т.е. должны касаться именно внешних проявлений, а не внутренних, мало смысла требовать от человека не гневаться, это его внутреннее состояние, если он его контролирует и никого не бьёт и не оскорбляет, то это не наше дело, мы конечно можем ему советовать так не делать, но запретить не вправе.

Подразумевается что принципы применяются к тем кто их разделяет, к нарушающим могут применяться санкции нарушающие какие-либо принципы.

=== Тезисы

Краткое изложение этичесих норм поделённое на две группы: запреты - жесткие нормы, выполнять которые обязательно, для обеспечения соблюдения которых может применяться насилие; советы - рекомендации к исполнению которых можно только призывать, но нельзя заставить.

==== Запреты

Запрещать жёстко имеет смысл только то, что приносит реальный вред человеку и обществу

. Не убивай
. Не причиняй вреда здоровью
. Не применяй насилия (в том числе не лишай свободы) и не угрожай его применением
. Не производи потомства без возможности вырастить его
. Не кради и не повреждай чужого имущества
. Не разрушай природу
. Не лги
. Не дурмань разум, как свой, так и чужой

==== Советы

Пока хаотично, нужно думать и наводить порядок

. Развивай свой разум и укрепляй здоровье
. Будь спокоен и рассудителен
. Уважай себя и других
. Будь хорошим семьянином, стремись, как и всё живое, оставить потомство, обеспечить выживание разума во вселенной
. Ставь цели и двигайся к ним
. Думай о последствиях своих действий (о своём будущем и будущем разумной жизни во вселенной), не живи сегодня в ущерб завтра, но и не ущемляй себя слишком сегодня ради жизни когда-то
. Помогай другим, но не поощряй паразитического образа жизни. Помогай тем кто нуждается, а не тем кто просит. "Давай удочку, а не рыбу". Помогай адресно, конкретному человеку, в судьбе которого ты готов поучаствовать (и знаешь, что он заслуживает помощи), а не неведомым попрошайкам
. Трудись на благо своё и общества
. Береги природу и её ресурсы
. Будь ответственным
. Будь умеренным - во всём соблюдай меру
. Будь рационально экономным
. Будь справедлив
. Будь скромен
. Расширяй свои познания и делись ими с другими
. Уважай частную жизнь
. Береги честь смолоду
. Мысли критически
. Стремись к свободе и самостоятельности
. Оценивай людей по делам
. Будь осторожен, не создавай/не увеличивай риски без необходимости
. Защищай себя, близких тебе людей, своё общество
. Защищай свои интересы в балансе с общими интересами

=== Более подробный разбор каждого тезиса

==== Запреты

===== Не убивай

Запрет на убийство членов своей общины/племени/веры - это самое ключевое правило человеческого общежития, оно встречается везде и у всех, и скорее всего без него невозможно построить стабильного общества, без него получим войну всех против всех, кровную месть и непрерывный страх.

Однако, разумно распространить правило не только на всё человечество, но и на любую иную разумную жизнь.

...

==== Советы

...

== Святыни и святые места

Так как карианство призывает опираться на разум, а разум есть инструмент для обработки информации, без которой он мало на что способен, то информация является одной из важнейших ценностей карианства. Знания о мире должны быть доступны всем. Изучение уже добытых знаний и открытие новых одна их важнейших задач любого карианина. Сокрытие, искажение информации считается недопустимым.
Особое значение имеют места/учреждения где хранят, передают или открывают новую информацию.

== Ссылки

. http://carians.org.ua["Первоисточник"]
. http://carians.livejournal.com/[Сообщество в ЖЖ] 
. http://vk.com/carian[Сообщество в ВК] 
. http://vk.com/club91553836[Альтернативное сообщество в ВК] 
. http://www.wikiznanie.ru/ru-wz/index.php/%D0%9A%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%81%D1%82%D0%B2%D0%BE[Статья на викизнании]

